### ISSUE TITLE
User: Profile Page UI

### ISSUE THREAD

**Issue by danmao1** [oss-slu/Seeing-is-Believing#41]
When an user tries to go to its own profile page or go to the settings of their account we get a page error of 404.

**Comment by akidSLU** [comment]
The aim of this issue is to design the Profile Page user interface. This UI should include some editable and non-editable information about a user.
Editable Items:
- Biography
- Pronouns
- Gravitar / profile picture
- Language (default = English)

Uneditable Items:
- Name
- Email
- Title (Student, Teacher, or Administrator)
- Organization
