### ISSUE TITLE
Create tables(except for user) in dev database.

### ISSUE THREAD

**Issue by LikhitaPulijala** [oss-slu/Seeing-is-Believing#69]
Similar to production database tables, create similar setup in dev database instance. Make sure the table names are similar in both environments. Dont do this manually, it should be done via code. Insert some data into all tables and the collections pattern must be same as prod.

**Comment by akidSLU** [comment]
Update for 10/16/23:
Progress has been made for create the proper collections for the development database. I've matched all the database fields except words and assignments. However, an issue has been encountered: which has impacted the creation of words and assignments(which I plan to create after words so I could include words in the assignment I try to create). 
There is no save button when on the add word page even when all the fields are filled out (I also checked on the deployed website and there is no save button like it says there should be in the code AddWordForm.js). Currently attempting to pinpoint this issue and will discuss on 10/17/23 group meetings.
Production Database Collections
<img width="349" alt="Screen Shot 2023-10-16 at 5 47 41 PM" src="https://github.com/oss-slu/Seeing-is-Believing/assets/112146951/6e4c9018-0ecf-48bb-bb0b-1891f6a04a9b">
Current State of Development Database Collections
<img width="303" alt="Screen Shot 2023-10-16 at 5 48 45 PM" src="https://github.com/oss-slu/Seeing-is-Believing/assets/112146951/7b8d35d7-d478-4937-9582-04bf1b3a1ca4">

**Comment by akidSLU** [comment]
Update:
After speaking with @LikhitaPulijala about the issues creating a word, it was decided that this problem was outside the scope of the goal of this issue so I manually added a word collection to the development database with all the proper fields.

There was an additional issue encountered when trying to create the assignment collection through creating an assignment with a teacher account through the application. The sidebar located on every page is loading the wrong set of items compared to what set of items are loaded for the teacher accounts in the deployed version of Seeing is Believing. I worked around this issue in order to create an assignment collection in the dev database through the application rather than by hand as with the word collection, however this new problem will need to be addressed eventually. 

As of now for this issue, the set of collections in the development database matches the collections in the production database and all fields for each collection also match in structure. 

Development Database:
![Screen Shot 2023-10-21 at 6 53 26 PM](https://github.com/oss-slu/Seeing-is-Believing/assets/112146951/db1f3835-b481-40d1-abf3-bf7b832a2dfc)
Production Database:
![Screen Shot 2023-10-21 at 6 47 55 PM](https://github.com/oss-slu/Seeing-is-Believing/assets/112146951/ca613189-370e-4db7-b5a3-c59390efb4f4)
