### ISSUE TITLE
Unable to Add Word in Admin account

### ISSUE THREAD

**Issue by LikhitaPulijala** [oss-slu/Seeing-is-Believing#82]
When admin is trying to add new word, the button is loading and unable to add word.

**Comment by OwenAThomasson** [comment]
Issue was solved without a PR required. Changes to the dev database were made to make this issue solved. We had to add a storage bucket to the dev database because that is where the audio files are stored. Besides that we had to set up Cross Origin Request permissions and now words can be successfully added to DB.
